app_settings:
  host: [0, 0, 0, 0]  # Default to all interfaces
  port: 8000
  base_url: "www.MyWeb.com"
  redis_url: "my_redis.url"

database:
  host: my-postgres

email_client:
  base_url: https://api.postmarkapp.com
  sender: pierre@go.com
  