name: Basic

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:latest
            ports:
              - 5432:5432
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: password
              POSTGRES_DB: craft
        steps:
            - uses: actions/checkout@v4

            - name: Run cargo test
              run: cargo test --verbose
            
            - name: Run Clippy
              run: cargo clippy --all-targets --all-features -- -D warnings
            
            - name: Run fmt check
              run: cargo fmt -- --check
